import { Module } from "./types";

// Modules mirror the PDF "Build Plan — Day by Day (3 Jun – 7 Jul)" exactly.
// Each build-plan row is one module; each row's steps are its subtasks.
export const INITIAL_MODULES: Module[] = [
  {
    id: 1,
    title: "APEX — CSI Generator API + Statutory + HexaComply (HSSB & KISB)",
    shortTitle: "APEX CSI + Statutory",
    phase: 1,
    dates: "3–5 Jun (Mon–Wed)",
    dateRange: { start: "2026-06-03", end: "2026-06-05" },
    status: "in_progress",
    progress: 0,
    notes: "APEX CSI Flow live as of 3 Jun; statutory module & HexaComply triggers building this week.",
    owner: "Asim + Ikhram",
    tags: ["Phase 1", "APEX", "Malaysia"],
    dependencies: [],
    subTasks: [
      { id: "1-1", title: "CSI Generator API integration (Ikhram)", completed: true },
      { id: "1-2", title: "Inbound CSI data → HexaFlow", completed: true },
      { id: "1-3", title: "Outbound payment confirmation → CSI app", completed: true },
      { id: "1-4", title: "Statutory: EPF (KWSP) for HSSB & KISB", completed: true },
      { id: "1-5", title: "Statutory: SOCSO (PERKESO) + EIS", completed: true },
      { id: "1-6", title: "Statutory: PCB/MTD", completed: false },
      { id: "1-7", title: "Statutory: HRDF", completed: false },
      { id: "1-8", title: "HexaComply Malaysia due dates & triggers corrected", completed: false },
    ],
  },
  {
    id: 2,
    title: "APEX Go-Live + End-to-End Test",
    shortTitle: "APEX Go-Live",
    phase: 1,
    dates: "8–9 Jun (Mon–Tue)",
    dateRange: { start: "2026-06-08", end: "2026-06-09" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim + Ikhram",
    tags: ["Phase 1", "APEX", "Test"],
    dependencies: ["Module 1 (APEX CSI + Statutory) built"],
    subTasks: [
      { id: "2-1", title: "Full cycle: CSI upload → approval", completed: false },
      { id: "2-2", title: "Maybank bank file → payment posted", completed: false },
      { id: "2-3", title: "Confirmation back to CSI app", completed: false },
      { id: "2-4", title: "Statutory module tested against HSSB", completed: false },
      { id: "2-5", title: "HexaComply Malaysia triggers verified live", completed: false },
    ],
  },
  {
    id: 3,
    title: "Internal Payroll — Malaysia Only (BrioHR → Zoho)",
    shortTitle: "Internal Payroll",
    phase: 1,
    dates: "10 Jun (Wed)",
    dateRange: { start: "2026-06-10", end: "2026-06-10" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 1", "Payroll", "Malaysia"],
    dependencies: ["BrioHR payroll register ready by 9 Jun EOD"],
    subTasks: [
      { id: "3-1", title: "BrioHR payroll register import", completed: false },
      { id: "3-2", title: "Calculation: basic, allowances, EPF/SOCSO deductions", completed: false },
      { id: "3-3", title: "HOF approval", completed: false },
      { id: "3-4", title: "Zoho Dr. Salary Payable / Cr. Bank auto-post", completed: false },
      { id: "3-5", title: "Maybank bank file generated", completed: false },
    ],
  },
  {
    id: 4,
    title: "CLEO — OPEX Approval Platform (Malaysia Vendors)",
    shortTitle: "CLEO OPEX",
    phase: 2,
    dates: "11 Jun (Thu)",
    dateRange: { start: "2026-06-11", end: "2026-06-11" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 2", "CLEO", "Controls", "AP"],
    dependencies: [],
    subTasks: [
      { id: "4-1", title: "PR raised", completed: false },
      { id: "4-2", title: "HOF review", completed: false },
      { id: "4-3", title: "Director approval (email token)", completed: false },
      { id: "4-4", title: "On approval: Zoho bill created (Dr. OH Expense / Cr. AP)", completed: false },
      { id: "4-5", title: "On payment: Zoho bill payment posted (Dr. AP / Cr. Bank)", completed: false },
      { id: "4-6", title: "Hard gate: no PIR without signed PR", completed: false },
      { id: "4-7", title: "Malaysia vendors only", completed: false },
    ],
  },
  {
    id: 5,
    title: "CLEO — Loan Payment Sub-module (Malaysia Facilities)",
    shortTitle: "CLEO Loans",
    phase: 2,
    dates: "12 Jun (Fri)",
    dateRange: { start: "2026-06-12", end: "2026-06-12" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 2", "CLEO", "Treasury"],
    dependencies: [],
    subTasks: [
      { id: "5-1", title: "Alliance Bank TL", completed: false },
      { id: "5-2", title: "HLB HP x2", completed: false },
      { id: "5-3", title: "CIMB WC", completed: false },
      { id: "5-4", title: "Maybank WC", completed: false },
      { id: "5-5", title: "Auto-triggered 25th each month", completed: false },
      { id: "5-6", title: "Dr. Interest Exp + Dr. CL Loan / Cr. Bank posted in Zoho", completed: false },
      { id: "5-7", title: "Loan statement stored in Dropbox", completed: false },
    ],
  },
  {
    id: 6,
    title: "Bank Reconciliation — Malaysia (Maybank, HSSB & KISB)",
    shortTitle: "Bank Recon",
    phase: 2,
    dates: "16–17 Jun (Mon–Tue)",
    dateRange: { start: "2026-06-16", end: "2026-06-17" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 2", "Recon", "Controls", "Malaysia"],
    dependencies: ["Maybank statement samples (HSSB & KISB) by 15 Jun"],
    subTasks: [
      { id: "6-1", title: "Maybank statement upload (PDF/CSV)", completed: false },
      { id: "6-2", title: "Auto-match vs Zoho transactions", completed: false },
      { id: "6-3", title: "Unmatched flagged with reason codes", completed: false },
      { id: "6-4", title: "Recon report generated", completed: false },
      { id: "6-5", title: "HSSB and KISB accounts covered", completed: false },
      { id: "6-6", title: "Target: completed by 2nd of each month automatically", completed: false },
    ],
  },
  {
    id: 7,
    title: "ARIA — AR Collection Cycle + Malaysia Project P&L",
    shortTitle: "ARIA Collections",
    phase: 3,
    dates: "18–19 Jun (Wed–Thu)",
    dateRange: { start: "2026-06-18", end: "2026-06-19" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 3", "ARIA", "AR"],
    dependencies: [],
    subTasks: [
      { id: "7-1", title: "Auto-reminders at 7/3/1 days before due", completed: false },
      { id: "7-2", title: "DAR auto-generated every Monday", completed: false },
      { id: "7-3", title: "Live AR aging dashboard", completed: false },
      { id: "7-4", title: "Project P&L — Jendela", completed: false },
      { id: "7-5", title: "Project P&L — Kuching", completed: false },
      { id: "7-6", title: "Project P&L — Sacofa (RM 6.4m)", completed: false },
    ],
  },
  {
    id: 8,
    title: "ARIA — Auto-Invoicing to Zoho from APEX",
    shortTitle: "ARIA Auto-Invoice",
    phase: 3,
    dates: "20 Jun (Fri)",
    dateRange: { start: "2026-06-20", end: "2026-06-20" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 3", "ARIA", "AR"],
    dependencies: ["Module 1 (APEX CSI) live"],
    subTasks: [
      { id: "8-1", title: "Trigger: Malaysia CSI approved + payroll report signed", completed: false },
      { id: "8-2", title: "Invoice auto-generated in Zoho (Dr. AR / Cr. Sales) within 48 hrs", completed: false },
      { id: "8-3", title: "Signed payroll report is a hard gate", completed: false },
      { id: "8-4", title: "Fixes the unsigned-report gap for HSSB", completed: false },
    ],
  },
  {
    id: 9,
    title: "Fund Flow Dashboard — Malaysia (HSSB & KISB)",
    shortTitle: "Fund Flow",
    phase: 3,
    dates: "23–24 Jun (Mon–Tue)",
    dateRange: { start: "2026-06-23", end: "2026-06-24" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 3", "Treasury", "Dashboard", "Malaysia"],
    dependencies: [],
    subTasks: [
      { id: "9-1", title: "Entity cash ladder — HSSB", completed: false },
      { id: "9-2", title: "Entity cash ladder — KISB", completed: false },
      { id: "9-3", title: "6-week rolling forecast from known obligations (CSI, statutory, loans, overheads)", completed: false },
      { id: "9-4", title: "T-5/T-3/T-1 payout alerts", completed: false },
      { id: "9-5", title: "EOR vs project fund separation enforced structurally", completed: false },
    ],
  },
  {
    id: 10,
    title: "Intercompany Matrix — Malaysia (KISB–HSSB)",
    shortTitle: "Interco Matrix",
    phase: 4,
    dates: "25–26 Jun (Wed–Thu)",
    dateRange: { start: "2026-06-25", end: "2026-06-26" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 4", "Consolidation", "Controls", "Malaysia"],
    dependencies: [],
    subTasks: [
      { id: "10-1", title: "KISB–HSSB balances auto-reconciled", completed: false },
      { id: "10-2", title: "Elimination journals prepared", completed: false },
      { id: "10-3", title: "TP markup validated per Malaysia transfer pricing rules", completed: false },
      { id: "10-4", title: "Mismatch flagged to CFO", completed: false },
      { id: "10-5", title: "Last working day reconciliation enforced automatically", completed: false },
    ],
  },
  {
    id: 11,
    title: "Balance Sheet Breakdowns + Accruals Engine — Malaysia",
    shortTitle: "BS + Accruals",
    phase: 4,
    dates: "27 Jun – 2 Jul (Fri+Mon–Wed)",
    dateRange: { start: "2026-06-27", end: "2026-07-02" },
    status: "not_started",
    progress: 0,
    notes: "8 accrual journals auto-posted on 1st and 4th. Target: close in 15 working days.",
    owner: "Asim",
    tags: ["Phase 4", "Accounting", "Close"],
    dependencies: [],
    subTasks: [
      { id: "11-1", title: "AR/AP aging auto-populated", completed: false },
      { id: "11-2", title: "Advances reconciliation", completed: false },
      { id: "11-3", title: "Prepayments", completed: false },
      { id: "11-4", title: "Statutory liabilities auto-populated", completed: false },
      { id: "11-5", title: "Accrual journal — Depreciation", completed: false },
      { id: "11-6", title: "Accrual journal — Amortization", completed: false },
      { id: "11-7", title: "Accrual journal — Tax provision", completed: false },
      { id: "11-8", title: "Accrual journal — Audit fees", completed: false },
      { id: "11-9", title: "Accrual journal — COGS", completed: false },
      { id: "11-10", title: "Accrual journal — WIP sales", completed: false },
      { id: "11-11", title: "Accrual journal — Office overheads", completed: false },
      { id: "11-12", title: "Accrual journal — Prepayments", completed: false },
      { id: "11-13", title: "Auto-post on 1st and 4th", completed: false },
      { id: "11-14", title: "Target: close in 15 working days", completed: false },
    ],
  },
  {
    id: 12,
    title: "Translation Reserve — Malaysia Entities Only (MFRS 121)",
    shortTitle: "FX Translation",
    phase: 4,
    dates: "3–4 Jul (Thu–Fri)",
    dateRange: { start: "2026-07-03", end: "2026-07-04" },
    status: "not_started",
    progress: 0,
    notes: "HSSB & KISB both MYR functional currency, so translation reserve is minimal.",
    owner: "Asim",
    tags: ["Phase 4", "Consolidation", "FX", "Malaysia"],
    dependencies: [],
    subTasks: [
      { id: "12-1", title: "HSSB & KISB MYR functional currency confirmed (reserve minimal)", completed: false },
      { id: "12-2", title: "Build framework for foreign entity consolidation", completed: false },
      { id: "12-3", title: "MFRS 121 compliant output structure in place", completed: false },
    ],
  },
  {
    id: 13,
    title: "Full Malaysia System Review — Director Presentation",
    shortTitle: "System Review",
    phase: 4,
    dates: "7 Jul (Mon)",
    dateRange: { start: "2026-07-07", end: "2026-07-07" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 4", "Review"],
    dependencies: ["All 12 prior modules completed"],
    subTasks: [
      { id: "13-1", title: "End-to-end test: APEX → CLEO → ARIA → Fund Flow → Bank Recon → Accruals → Interco", completed: false },
      { id: "13-2", title: "One full simulated cycle", completed: false },
      { id: "13-3", title: "Director presentation", completed: false },
      { id: "13-4", title: "Sign-off before replication sprint begins", completed: false },
    ],
  },
];

export const PHASE_LABELS: Record<number, string> = {
  1: "Phase 1 — CSI Operations",
  2: "Phase 2 — AP & Controls",
  3: "Phase 3 — ARIA & Fund Flow",
  4: "Phase 4 — Consolidation",
};

export const PHASE_DATES: Record<number, string> = {
  1: "3 – 10 Jun 2026",
  2: "11 – 17 Jun 2026",
  3: "18 – 24 Jun 2026",
  4: "25 Jun – 7 Jul 2026",
};

export const PHASE_COLORS: Record<number, { bg: string; border: string; badge: string; accent: string }> = {
  1: {
    bg: "from-pink-50 to-rose-50",
    border: "border-pink-200",
    badge: "bg-pink-100 text-pink-700",
    accent: "#E91E8C",
  },
  2: {
    bg: "from-purple-50 to-violet-50",
    border: "border-purple-200",
    badge: "bg-purple-100 text-purple-700",
    accent: "#9C27B0",
  },
  3: {
    bg: "from-blue-50 to-indigo-50",
    border: "border-blue-200",
    badge: "bg-blue-100 text-blue-700",
    accent: "#1565C0",
  },
  4: {
    bg: "from-indigo-50 to-slate-50",
    border: "border-indigo-200",
    badge: "bg-indigo-100 text-indigo-700",
    accent: "#0D47A1",
  },
};
