import { Module } from "./types";

export const INITIAL_MODULES: Module[] = [
  {
    id: 1,
    title: "CSI Flow — API Integration with CSI Generator",
    shortTitle: "CSI Flow API",
    phase: 1,
    dates: "3–5 Jun & 8–9 Jun",
    dateRange: { start: "2026-06-03", end: "2026-06-09" },
    status: "completed",
    progress: 100,
    notes: "CSI Flow (Hexa Finance Operations) is complete and live as of 3 June 2026.",
    owner: "Asim + Ikhram",
    tags: ["Live", "Phase 1", "Core"],
    dependencies: [],
    subTasks: [
      { id: "1-1", title: "API integration with CSI Generator", completed: true },
      { id: "1-2", title: "Inbound CSI data flow setup", completed: true },
      { id: "1-3", title: "Outbound payment confirmation webhook", completed: true },
      { id: "1-4", title: "Spreadsheet upload → validation pipeline", completed: true },
      { id: "1-5", title: "Maker-checker approval workflow", completed: true },
      { id: "1-6", title: "Zoho accrual journal auto-post", completed: true },
      { id: "1-7", title: "Maybank bank file generation", completed: true },
      { id: "1-8", title: "Payment posting & audit trail", completed: true },
      { id: "1-9", title: "Full cycle end-to-end test on HSSB", completed: true },
      { id: "1-10", title: "Confirmation flow back to CSI app", completed: true },
    ],
  },
  {
    id: 2,
    title: "Statutory Module — EPF, SOCSO, EIS, PCB/MTD, HRDF, SST (HSSB & KISB)",
    shortTitle: "Statutory Module",
    phase: 1,
    dates: "3–5 Jun",
    dateRange: { start: "2026-06-03", end: "2026-06-05" },
    status: "in_progress",
    progress: 40,
    notes: "Malaysia only — all obligations due 15th of following month. SST bi-monthly.",
    owner: "Asim",
    tags: ["Phase 1", "Compliance", "Malaysia"],
    dependencies: [],
    subTasks: [
      { id: "2-1", title: "EPF (KWSP) computation & file generation", completed: true },
      { id: "2-2", title: "SOCSO (PERKESO) + EIS filing", completed: true },
      { id: "2-3", title: "HRDF levy calculation", completed: false },
      { id: "2-4", title: "PCB/MTD monthly tax deduction", completed: false },
      { id: "2-5", title: "SST bi-monthly (last day of 2nd month)", completed: false },
      { id: "2-6", title: "Form E (31 Mar) & EA Form (28 Feb) generation", completed: false },
      { id: "2-7", title: "HexaComply Malaysia due dates & triggers corrected", completed: false },
      { id: "2-8", title: "Integration test — statutory tested on HSSB", completed: false },
    ],
  },
  {
    id: 3,
    title: "Internal Payroll — BrioHR Register, Approval & Zoho Auto-Post (Malaysia)",
    shortTitle: "Internal Payroll",
    phase: 1,
    dates: "10 Jun",
    dateRange: { start: "2026-06-10", end: "2026-06-10" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 1", "Payroll", "Malaysia"],
    dependencies: ["BrioHR payroll register ready by 9 Jun EOD", "Zoho API credentials confirmed"],
    subTasks: [
      { id: "3-1", title: "BrioHR payroll register integration", completed: false },
      { id: "3-2", title: "Calculation engine (basic, allowances, EPF/SOCSO deductions)", completed: false },
      { id: "3-3", title: "HOF approval workflow", completed: false },
      { id: "3-4", title: "Zoho Dr. Salary Payable / Cr. Bank auto-post", completed: false },
      { id: "3-5", title: "Maybank bank file generation for payroll", completed: false },
      { id: "3-6", title: "Payroll slip generation", completed: false },
    ],
  },
  {
    id: 4,
    title: "CLEO — OPEX Approval Platform (Malaysia Vendors)",
    shortTitle: "CLEO OPEX",
    phase: 2,
    dates: "11 Jun",
    dateRange: { start: "2026-06-11", end: "2026-06-11" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 2", "Controls", "AP", "CLEO"],
    dependencies: ["Zoho API credentials confirmed"],
    subTasks: [
      { id: "4-1", title: "PR creation form & submission workflow", completed: false },
      { id: "4-2", title: "HOF review step", completed: false },
      { id: "4-3", title: "Director approval via email token", completed: false },
      { id: "4-4", title: "Zoho bill created on approval — Dr. OH Expense / Cr. AP", completed: false },
      { id: "4-5", title: "Zoho bill payment posted — Dr. AP / Cr. Bank", completed: false },
      { id: "4-6", title: "Hard gate: no PIR without signed PR", completed: false },
      { id: "4-7", title: "BRN validation for vendor payments", completed: false },
    ],
  },
  {
    id: 5,
    title: "CLEO — Loan Payment Sub-module (Malaysia Facilities)",
    shortTitle: "CLEO Loans",
    phase: 2,
    dates: "12 Jun",
    dateRange: { start: "2026-06-12", end: "2026-06-12" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 2", "AP", "Treasury", "CLEO"],
    dependencies: ["Zoho API credentials confirmed"],
    subTasks: [
      { id: "5-1", title: "Alliance Bank TL schedule setup", completed: false },
      { id: "5-2", title: "HLB HP (x2 facilities) loan schedule", completed: false },
      { id: "5-3", title: "CIMB WC loan schedule", completed: false },
      { id: "5-4", title: "Maybank WC loan schedule", completed: false },
      { id: "5-5", title: "Auto-trigger on 25th of each month", completed: false },
      { id: "5-6", title: "Dr. Interest Exp + Dr. CL Loan / Cr. Bank auto-post", completed: false },
      { id: "5-7", title: "Loan statement stored in Dropbox", completed: false },
    ],
  },
  {
    id: 6,
    title: "Bank Reconciliation Automation — Maybank (HSSB & KISB)",
    shortTitle: "Bank Recon",
    phase: 2,
    dates: "16–17 Jun",
    dateRange: { start: "2026-06-16", end: "2026-06-17" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 2", "Controls", "Recon", "Malaysia"],
    dependencies: ["Maybank statement samples (HSSB & KISB) by 15 Jun"],
    subTasks: [
      { id: "6-1", title: "Maybank statement upload (PDF/CSV parser)", completed: false },
      { id: "6-2", title: "Auto-match transactions vs Zoho ledger", completed: false },
      { id: "6-3", title: "Unmatched items flagged with reason codes", completed: false },
      { id: "6-4", title: "Recon report generation with supporting docs", completed: false },
      { id: "6-5", title: "HSSB and KISB accounts covered", completed: false },
      { id: "6-6", title: "Target: recon done by 2nd of each month", completed: false },
    ],
  },
  {
    id: 7,
    title: "ARIA — AR Collection Cycle + Project P&L Dashboard",
    shortTitle: "ARIA Collections",
    phase: 3,
    dates: "18–19 Jun",
    dateRange: { start: "2026-06-18", end: "2026-06-19" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 3", "AR", "ARIA"],
    dependencies: [],
    subTasks: [
      { id: "7-1", title: "Auto-reminders at T-7 days", completed: false },
      { id: "7-2", title: "Auto-reminders at T-3 days", completed: false },
      { id: "7-3", title: "Auto-reminders at T-1 day", completed: false },
      { id: "7-4", title: "Overdue escalation workflow", completed: false },
      { id: "7-5", title: "DAR auto-generated every Monday", completed: false },
      { id: "7-6", title: "Live AR aging dashboard", completed: false },
      { id: "7-7", title: "Project P&L — Jendela", completed: false },
      { id: "7-8", title: "Project P&L — Kuching", completed: false },
      { id: "7-9", title: "Project P&L — Sacofa", completed: false },
    ],
  },
  {
    id: 8,
    title: "ARIA — Auto-Invoicing to Zoho from CSI",
    shortTitle: "ARIA Auto-Invoice",
    phase: 3,
    dates: "20 Jun",
    dateRange: { start: "2026-06-20", end: "2026-06-20" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 3", "AR", "ARIA"],
    dependencies: ["CSI Flow API (Module 1) live"],
    subTasks: [
      { id: "8-1", title: "CSI approved trigger for invoice creation", completed: false },
      { id: "8-2", title: "Signed payroll report hard gate enforcement", completed: false },
      { id: "8-3", title: "Invoice in Zoho — Dr. AR / Cr. Sales auto-post", completed: false },
      { id: "8-4", title: "48-hour SLA from CSI approval to invoice", completed: false },
      { id: "8-5", title: "Invoice PDF generation & email to client", completed: false },
    ],
  },
  {
    id: 9,
    title: "Fund Flow Dashboard — 6-Week Rolling Cash Forecast",
    shortTitle: "Fund Flow",
    phase: 3,
    dates: "23–24 Jun",
    dateRange: { start: "2026-06-23", end: "2026-06-24" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 3", "Treasury", "Dashboard", "Malaysia"],
    dependencies: [],
    subTasks: [
      { id: "9-1", title: "6-week rolling forecast from known obligations", completed: false },
      { id: "9-2", title: "HSSB entity cash ladder", completed: false },
      { id: "9-3", title: "KISB entity cash ladder", completed: false },
      { id: "9-4", title: "T-5 payout alert (5 days before, check if short)", completed: false },
      { id: "9-5", title: "T-3 payout alert", completed: false },
      { id: "9-6", title: "T-1 payout alert", completed: false },
      { id: "9-7", title: "EOR vs project fund separation enforced structurally", completed: false },
    ],
  },
  {
    id: 10,
    title: "Intercompany Matrix Automation — KISB–HSSB (Malaysia)",
    shortTitle: "Interco Matrix",
    phase: 4,
    dates: "25–26 Jun",
    dateRange: { start: "2026-06-25", end: "2026-06-26" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 4", "Consolidation", "Controls", "Malaysia"],
    dependencies: [],
    subTasks: [
      { id: "10-1", title: "KISB ↔ HSSB interco balance auto-reconciliation", completed: false },
      { id: "10-2", title: "Elimination journal preparation", completed: false },
      { id: "10-3", title: "TP markup validated per Malaysia transfer pricing rules", completed: false },
      { id: "10-4", title: "CFO mismatch alert & flagging", completed: false },
      { id: "10-5", title: "Last working day reconciliation enforced automatically", completed: false },
    ],
  },
  {
    id: 11,
    title: "Balance Sheet Breakdowns + Accruals Engine",
    shortTitle: "BS + Accruals",
    phase: 4,
    dates: "27 Jun – 2 Jul",
    dateRange: { start: "2026-06-27", end: "2026-07-02" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 4", "Accounting", "Close"],
    dependencies: [],
    subTasks: [
      { id: "11-1", title: "AR/AP aging schedules auto-populated", completed: false },
      { id: "11-2", title: "Advances reconciliation", completed: false },
      { id: "11-3", title: "Prepayments tracking & amortization", completed: false },
      { id: "11-4", title: "Statutory liabilities schedule", completed: false },
      { id: "11-5", title: "Depreciation journal (1st of month)", completed: false },
      { id: "11-6", title: "Tax provision accrual (4th of month)", completed: false },
      { id: "11-7", title: "COGS accrual journal", completed: false },
      { id: "11-8", title: "WIP sales accrual", completed: false },
      { id: "11-9", title: "Amortization journal (8 auto-posted monthly)", completed: false },
      { id: "11-10", title: "Month-end close target: 15 working days", completed: false },
    ],
  },
  {
    id: 12,
    title: "Translation Reserve Framework — MFRS 121 (Malaysia)",
    shortTitle: "FX Translation",
    phase: 4,
    dates: "3–4 Jul",
    dateRange: { start: "2026-07-03", end: "2026-07-04" },
    status: "not_started",
    progress: 0,
    notes: "HSSB & KISB both MYR functional currency — reserve minimal; build framework for foreign consolidation.",
    owner: "Asim",
    tags: ["Phase 4", "Consolidation", "FX", "Malaysia"],
    dependencies: [],
    subTasks: [
      { id: "12-1", title: "HSSB & KISB MYR functional currency confirmed", completed: false },
      { id: "12-2", title: "Monthly average rate — P&L translation logic", completed: false },
      { id: "12-3", title: "Closing rate — Balance Sheet translation logic", completed: false },
      { id: "12-4", title: "OCI / translation reserve computation", completed: false },
      { id: "12-5", title: "MFRS 121 compliant output structure", completed: false },
      { id: "12-6", title: "Framework ready for foreign entity consolidation", completed: false },
    ],
  },
  {
    id: 13,
    title: "Full System Review & End-to-End Test — Director Presentation",
    shortTitle: "System Review",
    phase: 4,
    dates: "7 Jul",
    dateRange: { start: "2026-07-07", end: "2026-07-07" },
    status: "not_started",
    progress: 0,
    notes: "",
    owner: "Asim",
    tags: ["Phase 4", "Review"],
    dependencies: ["All 12 modules completed"],
    subTasks: [
      { id: "13-1", title: "CSI Flow end-to-end verification", completed: false },
      { id: "13-2", title: "Statutory module full test", completed: false },
      { id: "13-3", title: "Payroll & PR modules verified", completed: false },
      { id: "13-4", title: "Bank recon & fund flow verified", completed: false },
      { id: "13-5", title: "ARIA invoicing & collections verified", completed: false },
      { id: "13-6", title: "Interco matrix & BS/accruals verified", completed: false },
      { id: "13-7", title: "FX translation & consolidation verified", completed: false },
      { id: "13-8", title: "Director presentation prepared", completed: false },
      { id: "13-9", title: "Sign-off from Director", completed: false },
    ],
  },
];

export const PHASE_LABELS: Record<number, string> = {
  1: "Phase 1 — CSI Operations",
  2: "Phase 2 — AP & Controls",
  3: "Phase 3 — ARIA & Fund Flow",
  4: "Phase 4 — Consolidation",
};

export const PHASE_DATES: Record<number, string> = {
  1: "3 – 9 Jun 2026",
  2: "10 – 17 Jun 2026",
  3: "18 – 24 Jun 2026",
  4: "25 Jun – 7 Jul 2026",
};

export const PHASE_COLORS: Record<number, { bg: string; border: string; badge: string; accent: string }> = {
  1: {
    bg: "from-pink-50 to-rose-50",
    border: "border-pink-200",
    badge: "bg-pink-100 text-pink-700",
    accent: "#E91E8C",
  },
  2: {
    bg: "from-purple-50 to-violet-50",
    border: "border-purple-200",
    badge: "bg-purple-100 text-purple-700",
    accent: "#9C27B0",
  },
  3: {
    bg: "from-blue-50 to-indigo-50",
    border: "border-blue-200",
    badge: "bg-blue-100 text-blue-700",
    accent: "#1565C0",
  },
  4: {
    bg: "from-indigo-50 to-slate-50",
    border: "border-indigo-200",
    badge: "bg-indigo-100 text-indigo-700",
    accent: "#0D47A1",
  },
};
